-- Core application schema for registrations, feedback, calendar, content,
-- pre-gallery, and dynamic gallery data.
-- This script is additive where possible so it can be run safely on an
-- existing Supabase project.

create table if not exists public.registrations (
    employee_code text primary key,
    full_name text not null,
    location text not null,
    organization text not null,
    department text not null,
    designation text not null,
    email text not null unique,
    sports_interested jsonb not null,
    other_sport text,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.registrations
    add column if not exists employee_code text,
    add column if not exists full_name text,
    add column if not exists location text,
    add column if not exists organization text,
    add column if not exists department text,
    add column if not exists designation text,
    add column if not exists email text,
    add column if not exists sports_interested jsonb,
    add column if not exists other_sport text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now());

create unique index if not exists registrations_email_key
    on public.registrations (email);

create index if not exists registrations_created_at_idx
    on public.registrations (created_at desc);

create table if not exists public.feedbacks (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    employee_code text,
    contact_number text,
    location text,
    organization text,
    department text,
    experience_rating integer not null check (experience_rating >= 1 and experience_rating <= 5),
    feedback_type text not null,
    message text not null,
    submitted_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.feedbacks
    add column if not exists name text,
    add column if not exists email text,
    add column if not exists employee_code text,
    add column if not exists contact_number text,
    add column if not exists location text,
    add column if not exists organization text,
    add column if not exists department text,
    add column if not exists experience_rating integer,
    add column if not exists feedback_type text,
    add column if not exists message text,
    add column if not exists submitted_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedbacks_experience_rating_check'
          and conrelid = 'public.feedbacks'::regclass
    ) then
        alter table public.feedbacks
            add constraint feedbacks_experience_rating_check
            check (experience_rating >= 1 and experience_rating <= 5);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedbacks_feedback_type_check'
          and conrelid = 'public.feedbacks'::regclass
    )
    and not exists (
        select 1
        from public.feedbacks
        where feedback_type is not null
          and lower(feedback_type) not in ('suggestion', 'complaint', 'appreciation')
    ) then
        alter table public.feedbacks
            add constraint feedbacks_feedback_type_check
            check (lower(feedback_type) in ('suggestion', 'complaint', 'appreciation'));
    end if;
end
$$;

create index if not exists feedbacks_submitted_at_idx
    on public.feedbacks (submitted_at desc);

create table if not exists public.calendar_events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    sport text not null default 'General',
    event_date date not null,
    event_time time,
    event_type text not null check (event_type in ('Internal', 'External', 'Corporate')),
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.calendar_events
    add column if not exists event_name text,
    add column if not exists sport text default 'General',
    add column if not exists event_date date,
    add column if not exists event_time time,
    add column if not exists event_type text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'calendar_events_event_type_check'
          and conrelid = 'public.calendar_events'::regclass
    )
    and not exists (
        select 1
        from public.calendar_events
        where event_type is not null
          and event_type not in ('Internal', 'External', 'Corporate')
    ) then
        alter table public.calendar_events
            add constraint calendar_events_event_type_check
            check (event_type in ('Internal', 'External', 'Corporate'));
    end if;
end
$$;

create index if not exists calendar_events_event_date_idx
    on public.calendar_events (event_date asc, event_time asc);

create table if not exists public.whats_new (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    icon_type text not null,
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.whats_new
    add column if not exists title text,
    add column if not exists description text,
    add column if not exists icon_type text,
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists whats_new_updated_at_idx
    on public.whats_new (updated_at desc);

create table if not exists public.upcoming_events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    event_date text not null,
    event_time text not null,
    event_venue text not null,
    event_image text not null,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.upcoming_events
    add column if not exists event_name text,
    add column if not exists event_date text,
    add column if not exists event_time text,
    add column if not exists event_venue text,
    add column if not exists event_image text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists upcoming_events_created_at_idx
    on public.upcoming_events (created_at desc);

create table if not exists public.hall_of_fame (
    id bigint generated by default as identity primary key,
    event_name text not null,
    event_date text not null,
    event_venue text not null,
    winner_name text not null,
    achievement_type text not null,
    event_image text not null,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.hall_of_fame
    add column if not exists event_name text,
    add column if not exists event_date text,
    add column if not exists event_venue text,
    add column if not exists winner_name text,
    add column if not exists achievement_type text,
    add column if not exists event_image text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists hall_of_fame_created_at_idx
    on public.hall_of_fame (created_at desc);

create table if not exists public.pregallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    display_order integer not null,
    uploaded_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.pregallery_images
    add column if not exists image_url text,
    add column if not exists display_order integer,
    add column if not exists uploaded_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'pregallery_images_display_order_check'
          and conrelid = 'public.pregallery_images'::regclass
    ) then
        alter table public.pregallery_images
            add constraint pregallery_images_display_order_check
            check (display_order between 1 and 3);
    end if;
end
$$;

create unique index if not exists pregallery_images_display_order_key
    on public.pregallery_images (display_order);

create table if not exists public.gallery_categories (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.gallery_categories
    add column if not exists name text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now());

create unique index if not exists gallery_categories_name_key
    on public.gallery_categories (name);

insert into public.gallery_categories (name)
values
    ('cricket'),
    ('football'),
    ('badminton'),
    ('lawn_tennis'),
    ('table_tennis'),
    ('workshops')
on conflict (name) do nothing;

create table if not exists public.gallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    category_id bigint not null references public.gallery_categories(id) on delete cascade,
    uploaded_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.gallery_images
    add column if not exists image_url text,
    add column if not exists category_id bigint,
    add column if not exists uploaded_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_images_category_id_fkey'
          and conrelid = 'public.gallery_images'::regclass
    ) then
        alter table public.gallery_images
            add constraint gallery_images_category_id_fkey
            foreign key (category_id) references public.gallery_categories(id) on delete cascade;
    end if;
end
$$;

create index if not exists gallery_images_category_uploaded_idx
    on public.gallery_images (category_id, uploaded_at desc);

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$;

do $$
begin
    if to_regclass('public.calendar_events') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_calendar_events_updated_at') then
        create trigger set_calendar_events_updated_at
            before update on public.calendar_events
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.whats_new') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_whats_new_updated_at') then
        create trigger set_whats_new_updated_at
            before update on public.whats_new
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.upcoming_events') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_upcoming_events_updated_at') then
        create trigger set_upcoming_events_updated_at
            before update on public.upcoming_events
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.hall_of_fame') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_hall_of_fame_updated_at') then
        create trigger set_hall_of_fame_updated_at
            before update on public.hall_of_fame
            for each row execute function public.set_row_updated_at();
    end if;
end
$$;

