-- Core application schema for registrations, feedback, calendar, content,
-- pre-gallery, and dynamic gallery data.
-- This script is additive where possible so it can be run safely on an
-- existing Supabase project.

create table if not exists public.registrations (
    employee_code text primary key,
    full_name text not null,
    location text not null,
    organization text not null,
    department text not null,
    designation text not null,
    email text not null unique,
    sports_interested jsonb not null,
    other_sport text,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.registrations
    add column if not exists employee_code text,
    add column if not exists full_name text,
    add column if not exists location text,
    add column if not exists organization text,
    add column if not exists department text,
    add column if not exists designation text,
    add column if not exists email text,
    add column if not exists sports_interested jsonb,
    add column if not exists other_sport text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now());

create unique index if not exists registrations_email_key
    on public.registrations (email);

create index if not exists registrations_created_at_idx
    on public.registrations (created_at desc);

create table if not exists public.feedbacks (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    employee_code text,
    contact_number text,
    location text,
    organization text,
    department text,
    experience_rating integer not null check (experience_rating >= 1 and experience_rating <= 5),
    feedback_type text not null,
    message text not null,
    submitted_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.feedbacks
    add column if not exists name text,
    add column if not exists email text,
    add column if not exists employee_code text,
    add column if not exists contact_number text,
    add column if not exists location text,
    add column if not exists organization text,
    add column if not exists department text,
    add column if not exists experience_rating integer,
    add column if not exists feedback_type text,
    add column if not exists message text,
    add column if not exists submitted_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedbacks_experience_rating_check'
          and conrelid = 'public.feedbacks'::regclass
    ) then
        alter table public.feedbacks
            add constraint feedbacks_experience_rating_check
            check (experience_rating >= 1 and experience_rating <= 5);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedbacks_feedback_type_check'
          and conrelid = 'public.feedbacks'::regclass
    )
    and not exists (
        select 1
        from public.feedbacks
        where feedback_type is not null
          and lower(feedback_type) not in ('suggestion', 'complaint', 'appreciation')
    ) then
        alter table public.feedbacks
            add constraint feedbacks_feedback_type_check
            check (lower(feedback_type) in ('suggestion', 'complaint', 'appreciation'));
    end if;
end
$$;

create index if not exists feedbacks_submitted_at_idx
    on public.feedbacks (submitted_at desc);

create table if not exists public.calendar_events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    sport text not null default 'General',
    event_date date not null,
    event_time time,
    event_type text not null check (event_type in ('Internal', 'External', 'Corporate')),
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.calendar_events
    add column if not exists event_name text,
    add column if not exists sport text default 'General',
    add column if not exists event_date date,
    add column if not exists event_time time,
    add column if not exists event_type text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'calendar_events_event_type_check'
          and conrelid = 'public.calendar_events'::regclass
    )
    and not exists (
        select 1
        from public.calendar_events
        where event_type is not null
          and event_type not in ('Internal', 'External', 'Corporate')
    ) then
        alter table public.calendar_events
            add constraint calendar_events_event_type_check
            check (event_type in ('Internal', 'External', 'Corporate'));
    end if;
end
$$;

create index if not exists calendar_events_event_date_idx
    on public.calendar_events (event_date asc, event_time asc);

create table if not exists public.calendar_settings (
    id bigint primary key default 1,
    fy_label text not null default 'FY 25-26',
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now()),
    constraint calendar_settings_single_row check (id = 1),
    constraint calendar_settings_fy_label_not_blank check (char_length(btrim(fy_label)) > 0)
);

alter table if exists public.calendar_settings
    add column if not exists fy_label text default 'FY 25-26',
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

insert into public.calendar_settings (id, fy_label)
values (1, 'FY 25-26')
on conflict (id) do nothing;

create table if not exists public.whats_new (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    icon_type text not null,
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.whats_new
    add column if not exists title text,
    add column if not exists description text,
    add column if not exists icon_type text,
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists whats_new_updated_at_idx
    on public.whats_new (updated_at desc);

create table if not exists public.upcoming_events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    event_date text not null,
    event_time text not null,
    event_venue text not null,
    event_image text not null,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.upcoming_events
    add column if not exists event_name text,
    add column if not exists event_date text,
    add column if not exists event_time text,
    add column if not exists event_venue text,
    add column if not exists event_image text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists upcoming_events_created_at_idx
    on public.upcoming_events (created_at desc);

create table if not exists public.hall_of_fame (
    id bigint generated by default as identity primary key,
    event_name text not null,
    event_date text not null,
    event_venue text not null,
    winner_name text not null,
    achievement_type text not null,
    event_image text not null,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.hall_of_fame
    add column if not exists event_name text,
    add column if not exists event_date text,
    add column if not exists event_venue text,
    add column if not exists winner_name text,
    add column if not exists achievement_type text,
    add column if not exists event_image text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

create index if not exists hall_of_fame_created_at_idx
    on public.hall_of_fame (created_at desc);

create table if not exists public.pregallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    display_order integer not null,
    uploaded_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.pregallery_images
    add column if not exists image_url text,
    add column if not exists display_order integer,
    add column if not exists uploaded_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'pregallery_images_display_order_check'
          and conrelid = 'public.pregallery_images'::regclass
    ) then
        alter table public.pregallery_images
            add constraint pregallery_images_display_order_check
            check (display_order between 1 and 3);
    end if;
end
$$;

create unique index if not exists pregallery_images_display_order_key
    on public.pregallery_images (display_order);

create table if not exists public.gallery_categories (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.gallery_categories
    add column if not exists name text,
    add column if not exists created_at timestamptz default timezone('utc'::text, now());

create unique index if not exists gallery_categories_name_key
    on public.gallery_categories (name);

insert into public.gallery_categories (name)
values
    ('cricket'),
    ('football'),
    ('badminton'),
    ('lawn_tennis'),
    ('table_tennis'),
    ('workshops')
on conflict (name) do nothing;

create table if not exists public.gallery_folders (
    id bigint generated by default as identity primary key,
    name text not null,
    category_id bigint not null references public.gallery_categories(id) on delete cascade,
    parent_folder_id bigint references public.gallery_folders(id) on delete restrict,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.gallery_folders
    add column if not exists name text,
    add column if not exists category_id bigint,
    add column if not exists parent_folder_id bigint,
    add column if not exists created_at timestamptz default timezone('utc'::text, now()),
    add column if not exists updated_at timestamptz default timezone('utc'::text, now());

update public.gallery_folders
set
    name = btrim(coalesce(name, '')),
    created_at = coalesce(created_at, timezone('utc'::text, now())),
    updated_at = coalesce(updated_at, created_at, timezone('utc'::text, now()))
where
    name is null
    or name <> btrim(name)
    or created_at is null
    or updated_at is null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_category_id_fkey'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_category_id_fkey
            foreign key (category_id) references public.gallery_categories(id) on delete cascade;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_parent_folder_id_fkey'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_parent_folder_id_fkey
            foreign key (parent_folder_id) references public.gallery_folders(id) on delete restrict;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_name_not_blank'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_name_not_blank
            check (char_length(btrim(name)) > 0);
    end if;
end
$$;

create index if not exists gallery_folders_category_id_idx
    on public.gallery_folders (category_id);

create index if not exists gallery_folders_parent_folder_id_idx
    on public.gallery_folders (parent_folder_id);

create unique index if not exists gallery_folders_unique_sibling_name_idx
    on public.gallery_folders (category_id, coalesce(parent_folder_id, 0), lower(btrim(name)));

create table if not exists public.gallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    category_id bigint not null references public.gallery_categories(id) on delete cascade,
    uploaded_at timestamptz not null default timezone('utc'::text, now())
);

alter table if exists public.gallery_images
    add column if not exists image_url text,
    add column if not exists category_id bigint,
    add column if not exists folder_id bigint,
    add column if not exists uploaded_at timestamptz default timezone('utc'::text, now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_images_category_id_fkey'
          and conrelid = 'public.gallery_images'::regclass
    ) then
        alter table public.gallery_images
            add constraint gallery_images_category_id_fkey
            foreign key (category_id) references public.gallery_categories(id) on delete cascade;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_images_folder_id_fkey'
          and conrelid = 'public.gallery_images'::regclass
    ) then
        alter table public.gallery_images
            add constraint gallery_images_folder_id_fkey
            foreign key (folder_id) references public.gallery_folders(id) on delete restrict;
    end if;
end
$$;

create index if not exists gallery_images_category_uploaded_idx
    on public.gallery_images (category_id, uploaded_at desc);

create index if not exists gallery_images_folder_id_idx
    on public.gallery_images (folder_id);

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$;

do $$
begin
    if to_regclass('public.calendar_events') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_calendar_events_updated_at') then
        create trigger set_calendar_events_updated_at
            before update on public.calendar_events
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.calendar_settings') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_calendar_settings_updated_at') then
        create trigger set_calendar_settings_updated_at
            before update on public.calendar_settings
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.whats_new') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_whats_new_updated_at') then
        create trigger set_whats_new_updated_at
            before update on public.whats_new
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.upcoming_events') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_upcoming_events_updated_at') then
        create trigger set_upcoming_events_updated_at
            before update on public.upcoming_events
            for each row execute function public.set_row_updated_at();
    end if;

    if to_regclass('public.hall_of_fame') is not null
       and not exists (select 1 from pg_trigger where tgname = 'set_hall_of_fame_updated_at') then
        create trigger set_hall_of_fame_updated_at
            before update on public.hall_of_fame
            for each row execute function public.set_row_updated_at();
    end if;
end
$$;

create or replace function public.validate_gallery_folder_hierarchy()
returns trigger
language plpgsql
as $$
declare
    parent_category_id bigint;
begin
    new.name = btrim(coalesce(new.name, ''));

    if new.name = '' then
        raise exception 'Folder name cannot be empty.';
    end if;

    if new.parent_folder_id is null then
        return new;
    end if;

    if new.id is not null and new.parent_folder_id = new.id then
        raise exception 'A folder cannot be its own parent.';
    end if;

    select category_id
    into parent_category_id
    from public.gallery_folders
    where id = new.parent_folder_id;

    if parent_category_id is null then
        raise exception 'Selected parent folder does not exist.';
    end if;

    if parent_category_id <> new.category_id then
        raise exception 'Parent folder must belong to the same gallery category.';
    end if;

    if new.id is not null and exists (
        with recursive parent_chain as (
            select id, parent_folder_id
            from public.gallery_folders
            where id = new.parent_folder_id

            union all

            select folder.id, folder.parent_folder_id
            from public.gallery_folders as folder
            inner join parent_chain on folder.id = parent_chain.parent_folder_id
        )
        select 1
        from parent_chain
        where id = new.id
    ) then
        raise exception 'A folder cannot be moved inside its own descendants.';
    end if;

    return new;
end;
$$;

create or replace function public.validate_gallery_image_folder_assignment()
returns trigger
language plpgsql
as $$
declare
    folder_category_id bigint;
begin
    if new.folder_id is null then
        return new;
    end if;

    select category_id
    into folder_category_id
    from public.gallery_folders
    where id = new.folder_id;

    if folder_category_id is null then
        raise exception 'Selected gallery folder does not exist.';
    end if;

    if folder_category_id <> new.category_id then
        raise exception 'Selected gallery folder must belong to the same category.';
    end if;

    return new;
end;
$$;

create or replace function public.prevent_deleting_nonempty_gallery_folder()
returns trigger
language plpgsql
as $$
begin
    if exists (
        select 1
        from public.gallery_folders
        where parent_folder_id = old.id
    ) or exists (
        select 1
        from public.gallery_images
        where folder_id = old.id
    ) then
        raise exception 'Cannot delete folder because it contains sub-folders or images.';
    end if;

    return old;
end;
$$;

drop trigger if exists validate_gallery_folder_hierarchy on public.gallery_folders;
create trigger validate_gallery_folder_hierarchy
    before insert or update on public.gallery_folders
    for each row execute function public.validate_gallery_folder_hierarchy();

drop trigger if exists set_gallery_folders_updated_at on public.gallery_folders;
create trigger set_gallery_folders_updated_at
    before update on public.gallery_folders
    for each row execute function public.set_row_updated_at();

drop trigger if exists validate_gallery_image_folder_assignment on public.gallery_images;
create trigger validate_gallery_image_folder_assignment
    before insert or update on public.gallery_images
    for each row execute function public.validate_gallery_image_folder_assignment();

drop trigger if exists prevent_deleting_nonempty_gallery_folder on public.gallery_folders;
create trigger prevent_deleting_nonempty_gallery_folder
    before delete on public.gallery_folders
    for each row execute function public.prevent_deleting_nonempty_gallery_folder();

