create table if not exists public.gallery_categories (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists gallery_categories_name_key
    on public.gallery_categories (name);

insert into public.gallery_categories (name)
values
    ('cricket'),
    ('football'),
    ('badminton'),
    ('lawn_tennis'),
    ('table_tennis'),
    ('workshops')
on conflict (name) do nothing;

create table if not exists public.gallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    category_id bigint not null references public.gallery_categories(id) on delete cascade,
    uploaded_at timestamptz not null default timezone('utc', now())
);

create index if not exists gallery_images_category_uploaded_idx
    on public.gallery_images (category_id, uploaded_at desc);

alter table public.gallery_categories enable row level security;
alter table public.gallery_images enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_categories'
          and policyname = 'Public can view gallery categories'
    ) then
        create policy "Public can view gallery categories"
            on public.gallery_categories
            for select
            to public
            using (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_categories'
          and policyname = 'Authenticated users can manage gallery categories'
    ) then
        create policy "Authenticated users can manage gallery categories"
            on public.gallery_categories
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_images'
          and policyname = 'Public can view gallery images'
    ) then
        create policy "Public can view gallery images"
            on public.gallery_images
            for select
            to public
            using (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_images'
          and policyname = 'Authenticated users can manage gallery images'
    ) then
        create policy "Authenticated users can manage gallery images"
            on public.gallery_images
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;

insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do nothing;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Public can view gallery storage objects'
    ) then
        create policy "Public can view gallery storage objects"
            on storage.objects
            for select
            to public
            using (bucket_id = 'gallery-images');
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Authenticated users can upload gallery storage objects'
    ) then
        create policy "Authenticated users can upload gallery storage objects"
            on storage.objects
            for insert
            to authenticated
            with check (bucket_id = 'gallery-images');
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Authenticated users can delete gallery storage objects'
    ) then
        create policy "Authenticated users can delete gallery storage objects"
            on storage.objects
            for delete
            to authenticated
            using (bucket_id = 'gallery-images');
    end if;
end
$$;


