create table if not exists public.pregallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    display_order integer not null,
    uploaded_at timestamptz not null default timezone('utc', now())
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'pregallery_images_display_order_check'
          and conrelid = 'public.pregallery_images'::regclass
    ) then
        alter table public.pregallery_images
            add constraint pregallery_images_display_order_check
            check (display_order between 1 and 3);
    end if;
end
$$;

create unique index if not exists pregallery_images_display_order_key
    on public.pregallery_images (display_order);

alter table public.pregallery_images enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'pregallery_images'
          and policyname = 'Public can view pregallery images'
    ) then
        create policy "Public can view pregallery images"
            on public.pregallery_images
            for select
            to public
            using (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'pregallery_images'
          and policyname = 'Authenticated users can manage pregallery images'
    ) then
        create policy "Authenticated users can manage pregallery images"
            on public.pregallery_images
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;

insert into storage.buckets (id, name, public)
values ('pregallery-images', 'pregallery-images', true)
on conflict (id) do nothing;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Public can view pregallery storage objects'
    ) then
        create policy "Public can view pregallery storage objects"
            on storage.objects
            for select
            to public
            using (bucket_id = 'pregallery-images');
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Authenticated users can upload pregallery storage objects'
    ) then
        create policy "Authenticated users can upload pregallery storage objects"
            on storage.objects
            for insert
            to authenticated
            with check (bucket_id = 'pregallery-images');
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Authenticated users can delete pregallery storage objects'
    ) then
        create policy "Authenticated users can delete pregallery storage objects"
            on storage.objects
            for delete
            to authenticated
            using (bucket_id = 'pregallery-images');
    end if;
end
$$;


