create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create table if not exists public.gallery_folders (
    id bigint generated by default as identity primary key,
    name text not null,
    category_id bigint not null references public.gallery_categories(id) on delete cascade,
    parent_folder_id bigint references public.gallery_folders(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.gallery_folders
    add column if not exists name text,
    add column if not exists category_id bigint,
    add column if not exists parent_folder_id bigint,
    add column if not exists created_at timestamptz default timezone('utc', now()),
    add column if not exists updated_at timestamptz default timezone('utc', now());

update public.gallery_folders
set
    name = btrim(coalesce(name, '')),
    created_at = coalesce(created_at, timezone('utc', now())),
    updated_at = coalesce(updated_at, created_at, timezone('utc', now()))
where
    name is null
    or name <> btrim(name)
    or created_at is null
    or updated_at is null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_category_id_fkey'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_category_id_fkey
            foreign key (category_id) references public.gallery_categories(id) on delete cascade;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_parent_folder_id_fkey'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_parent_folder_id_fkey
            foreign key (parent_folder_id) references public.gallery_folders(id) on delete restrict;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_folders_name_not_blank'
          and conrelid = 'public.gallery_folders'::regclass
    ) then
        alter table public.gallery_folders
            add constraint gallery_folders_name_not_blank
            check (char_length(btrim(name)) > 0);
    end if;
end
$$;

create index if not exists gallery_folders_category_id_idx
    on public.gallery_folders (category_id);

create index if not exists gallery_folders_parent_folder_id_idx
    on public.gallery_folders (parent_folder_id);

create unique index if not exists gallery_folders_unique_sibling_name_idx
    on public.gallery_folders (category_id, coalesce(parent_folder_id, 0), lower(btrim(name)));

create or replace function public.validate_gallery_folder_hierarchy()
returns trigger
language plpgsql
as $$
declare
    parent_category_id bigint;
begin
    new.name = btrim(coalesce(new.name, ''));

    if new.name = '' then
        raise exception 'Folder name cannot be empty.';
    end if;

    if new.parent_folder_id is null then
        return new;
    end if;

    if new.id is not null and new.parent_folder_id = new.id then
        raise exception 'A folder cannot be its own parent.';
    end if;

    select category_id
    into parent_category_id
    from public.gallery_folders
    where id = new.parent_folder_id;

    if parent_category_id is null then
        raise exception 'Selected parent folder does not exist.';
    end if;

    if parent_category_id <> new.category_id then
        raise exception 'Parent folder must belong to the same gallery category.';
    end if;

    if new.id is not null and exists (
        with recursive parent_chain as (
            select id, parent_folder_id
            from public.gallery_folders
            where id = new.parent_folder_id

            union all

            select folder.id, folder.parent_folder_id
            from public.gallery_folders as folder
            inner join parent_chain on folder.id = parent_chain.parent_folder_id
        )
        select 1
        from parent_chain
        where id = new.id
    ) then
        raise exception 'A folder cannot be moved inside its own descendants.';
    end if;

    return new;
end;
$$;

drop trigger if exists validate_gallery_folder_hierarchy on public.gallery_folders;

create trigger validate_gallery_folder_hierarchy
    before insert or update on public.gallery_folders
    for each row execute function public.validate_gallery_folder_hierarchy();

drop trigger if exists set_gallery_folders_updated_at on public.gallery_folders;

create trigger set_gallery_folders_updated_at
    before update on public.gallery_folders
    for each row execute function public.set_row_updated_at();

alter table public.gallery_images
    add column if not exists folder_id bigint;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'gallery_images_folder_id_fkey'
          and conrelid = 'public.gallery_images'::regclass
    ) then
        alter table public.gallery_images
            add constraint gallery_images_folder_id_fkey
            foreign key (folder_id) references public.gallery_folders(id) on delete restrict;
    end if;
end
$$;

create index if not exists gallery_images_folder_id_idx
    on public.gallery_images (folder_id);

create or replace function public.validate_gallery_image_folder_assignment()
returns trigger
language plpgsql
as $$
declare
    folder_category_id bigint;
begin
    if new.folder_id is null then
        return new;
    end if;

    select category_id
    into folder_category_id
    from public.gallery_folders
    where id = new.folder_id;

    if folder_category_id is null then
        raise exception 'Selected gallery folder does not exist.';
    end if;

    if folder_category_id <> new.category_id then
        raise exception 'Selected gallery folder must belong to the same category.';
    end if;

    return new;
end;
$$;

drop trigger if exists validate_gallery_image_folder_assignment on public.gallery_images;

create trigger validate_gallery_image_folder_assignment
    before insert or update on public.gallery_images
    for each row execute function public.validate_gallery_image_folder_assignment();

create or replace function public.prevent_deleting_nonempty_gallery_folder()
returns trigger
language plpgsql
as $$
begin
    if exists (
        select 1
        from public.gallery_folders
        where parent_folder_id = old.id
    ) or exists (
        select 1
        from public.gallery_images
        where folder_id = old.id
    ) then
        raise exception 'Cannot delete folder because it contains sub-folders or images.';
    end if;

    return old;
end;
$$;

drop trigger if exists prevent_deleting_nonempty_gallery_folder on public.gallery_folders;

create trigger prevent_deleting_nonempty_gallery_folder
    before delete on public.gallery_folders
    for each row execute function public.prevent_deleting_nonempty_gallery_folder();

alter table public.gallery_folders enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_folders'
          and policyname = 'Public can view gallery folders'
    ) then
        create policy "Public can view gallery folders"
            on public.gallery_folders
            for select
            to public
            using (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'gallery_folders'
          and policyname = 'Authenticated users can manage gallery folders'
    ) then
        create policy "Authenticated users can manage gallery folders"
            on public.gallery_folders
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;
